namespace ReactiveBinding
{
    /// <summary>
    /// Interface for reactive data binding observers.
    /// Classes implementing this interface can use [ReactiveSource] and [ReactiveBind] attributes.
    /// The Source Generator will automatically implement the ObserveChanges() method.
    /// </summary>
    public interface IReactiveObserver
    {
        /// <summary>
        /// Observes data changes and triggers bound callbacks.
        /// This method is auto-generated by the Source Generator.
        /// Call this method manually to check for data changes.
        /// On first call, all callbacks are triggered with default as oldValue.
        /// </summary>
        void ObserveChanges();
    }
}
