using Microsoft.CodeAnalysis;

namespace ReactiveBinding.Generator;

internal static class DiagnosticDescriptors
{
    private const string Category = "ReactiveBinding";

    // ReactiveBinding diagnostics (RB10001-RB10026)
    // Class-level errors
    public static readonly DiagnosticDescriptor RB10001_ClassNotPartial = new(
        id: "RB10001",
        title: "Class not partial",
        messageFormat: "Class '{0}' with ReactiveBind must be declared as partial",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor RB10002_ClassNotImplementInterface = new(
        id: "RB10002",
        title: "Class not implementing IReactiveObserver",
        messageFormat: "Class '{0}' with ReactiveBind must implement IReactiveObserver interface",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor RB10003_ThrottleInvalidValue = new(
        id: "RB10003",
        title: "Invalid ReactiveThrottle value",
        messageFormat: "ReactiveThrottle value must be >= 1, got {0}",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor RB10004_ThrottleWithoutInterface = new(
        id: "RB10004",
        title: "ReactiveThrottle without IReactiveObserver",
        messageFormat: "Class '{0}' has ReactiveThrottle but does not implement IReactiveObserver",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor RB10005_ManualObserveChanges = new(
        id: "RB10005",
        title: "Manual ObserveChanges implementation",
        messageFormat: "Method '{0}' in class '{1}' is auto-generated by the source generator and must not be manually implemented",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor RB10006_ManualResetChanges = new(
        id: "RB10006",
        title: "Manual ResetChanges implementation",
        messageFormat: "Method '{0}' in class '{1}' is auto-generated by the source generator and must not be manually implemented",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    // General source/bind diagnostics
    public static readonly DiagnosticDescriptor RB10007_UnmatchedSource = new(
        id: "RB10007",
        title: "Unmatched ReactiveSource",
        messageFormat: "ReactiveSource '{0}' has no corresponding ReactiveBind",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor RB10008_UnmatchedBind = new(
        id: "RB10008",
        title: "Unmatched ReactiveBind",
        messageFormat: "ReactiveBind on method '{0}' references non-existent sources: {1}",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor RB10009_ObserveChangesNotCalled = new(
        id: "RB10009",
        title: "ObserveChanges not called",
        messageFormat: "Class '{0}' implements IReactiveObserver but does not call ObserveChanges(). Please call ObserveChanges() in your code, or add [ReactiveObserveIgnore] if it is called externally.",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    // ReactiveSource errors
    public static readonly DiagnosticDescriptor RB10010_MethodReturnsVoid = new(
        id: "RB10010",
        title: "ReactiveSource method returns void",
        messageFormat: "ReactiveSource method '{0}' must have a return type (cannot be void)",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor RB10011_PropertyNoGetter = new(
        id: "RB10011",
        title: "ReactiveSource property has no getter",
        messageFormat: "ReactiveSource property '{0}' must have a getter",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor RB10012_MethodHasParameters = new(
        id: "RB10012",
        title: "ReactiveSource method has parameters",
        messageFormat: "ReactiveSource method '{0}' must have no parameters",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor RB10013_UnsupportedSourceType = new(
        id: "RB10013",
        title: "Unsupported ReactiveSource type",
        messageFormat: "ReactiveSource '{0}' has unsupported type '{1}'. Only primitive types, structs, and IVersion types are supported",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor RB10014_StructMissingEqualityOperator = new(
        id: "RB10014",
        title: "Struct missing equality operator",
        messageFormat: "ReactiveSource '{0}' uses struct type '{1}' which must implement == and != operators",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor RB10015_DuplicateSourceIdentifier = new(
        id: "RB10015",
        title: "Duplicate reactive source identifier",
        messageFormat: "Class '{0}' declares multiple [ReactiveSource] members named '{1}'. ReactiveBind identifies sources by name, so overloaded or duplicate source names are not supported.",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    // ReactiveBind errors
    public static readonly DiagnosticDescriptor RB10016_BindEmptyIds = new(
        id: "RB10016",
        title: "ReactiveBind has no identities",
        messageFormat: "ReactiveBind on method '{0}' must specify at least one source identity",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor RB10017_MethodIsStatic = new(
        id: "RB10017",
        title: "ReactiveBind method is static",
        messageFormat: "ReactiveBind method '{0}' cannot be static",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor RB10018_MethodNotVoid = new(
        id: "RB10018",
        title: "ReactiveBind method does not return void",
        messageFormat: "ReactiveBind method '{0}' must return void",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor RB10019_InvalidParameterCount = new(
        id: "RB10019",
        title: "Invalid parameter count",
        messageFormat: "ReactiveBind method '{0}' binds {1} sources but has {2} parameters. Valid signatures: {3}",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor RB10020_ParameterTypeMismatch = new(
        id: "RB10020",
        title: "Parameter type mismatch",
        messageFormat: "ReactiveBind method '{0}' parameter {1} has type '{2}' but source has type '{3}'",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor RB10021_DuplicateIds = new(
        id: "RB10021",
        title: "Duplicate identities in ReactiveBind",
        messageFormat: "ReactiveBind on method '{0}' has duplicate identities: {1}",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor RB10022_NotUsingNameof = new(
        id: "RB10022",
        title: "ReactiveBind not using nameof()",
        messageFormat: "ReactiveBind on method '{0}' must use nameof() expressions for source identities",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor RB10023_NoSourcesInferred = new(
        id: "RB10023",
        title: "No ReactiveSource found in method body",
        messageFormat: "ReactiveBind on method '{0}' uses auto-inference but no ReactiveSource members are referenced in the method body",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor RB10024_AutoInferredWithParameters = new(
        id: "RB10024",
        title: "Auto-inferred ReactiveBind cannot have parameters",
        messageFormat: "ReactiveBind on method '{0}' uses auto-inference and must have no parameters",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor RB10025_SourceNotMarked = new(
        id: "RB10025",
        title: "Referenced member not marked with ReactiveSource",
        messageFormat: "ReactiveBind on method '{0}' references '{1}' which exists but is not marked with [ReactiveSource]",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor RB10026_UnsupportedCallbackSignature = new(
        id: "RB10026",
        title: "Unsupported ReactiveBind callback signature",
        messageFormat: "ReactiveBind method '{0}' cannot be generic and cannot use ref, out, or in parameters",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    // VersionField class-level errors
    public static readonly DiagnosticDescriptor VF10001_ClassNotPartial = new(
        id: "VF10001",
        title: "Class not partial",
        messageFormat: "Class '{0}' with VersionField must be declared as partial",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor VF10002_ClassNotImplementInterface = new(
        id: "VF10002",
        title: "Class not implementing IVersion",
        messageFormat: "Class '{0}' with VersionField must implement IVersion interface",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor VF10003_VersionInheritanceNotSupported = new(
        id: "VF10003",
        title: "VersionField inheritance is not supported",
        messageFormat: "Class '{0}' inherits from '{1}', which already implements IVersion. " +
                       "VersionField/IVersionSync inheritance is not supported; use composition instead.",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor VF10004_GeneratedMemberConflict = new(
        id: "VF10004",
        title: "Member conflicts with generated VersionField state",
        messageFormat: "Class '{0}' already declares reserved member '{1}', which conflicts with VersionField generated code. Remove or rename the member.",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    // VersionField field-level errors
    public static readonly DiagnosticDescriptor VF10005_FieldNotPrefixed = new(
        id: "VF10005",
        title: "Field missing __ prefix",
        messageFormat: "VersionField '{0}' must have '__' prefix",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor VF10006_FieldNotPrivate = new(
        id: "VF10006",
        title: "Field not private",
        messageFormat: "VersionField '{0}' must be private",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor VF10007_PropertyAlreadyExists = new(
        id: "VF10007",
        title: "Property already exists",
        messageFormat: "Property '{0}' already exists, cannot generate from field '{1}'",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor VF10008_UnsupportedFieldModifier = new(
        id: "VF10008",
        title: "Unsupported VersionField modifier",
        messageFormat: "VersionField '{0}' cannot be static, const, or readonly because its generated property must mutate per-instance backing state",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor VF10009_InvalidPropertyName = new(
        id: "VF10009",
        title: "Invalid generated property name",
        messageFormat: "VersionField '{0}' would generate invalid C# property name '{1}'",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    // VersionField usage errors
    public static readonly DiagnosticDescriptor VF10010_DirectFieldAccess = new(
        id: "VF10010",
        title: "Direct access to VersionField backing field",
        messageFormat: "Field '{0}' is marked with [VersionField] and should only be accessed through the generated property '{1}'. Direct access bypasses version tracking.",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor VF10011_FieldHasInitializer = new(
        id: "VF10011",
        title: "VersionField must not have a default value initializer",
        messageFormat: "VersionField '{0}' must not have a default value initializer. Assign through the generated property '{1}' instead.",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor VF10012_InternalVersionMemberAccess = new(
        id: "VF10012",
        title: "Version protocol member access not allowed",
        messageFormat: "Version protocol member '{0}' is reserved for generated code and ReactiveBinding runtime infrastructure and cannot be accessed from user code.",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor VF10013_InvalidVersionPropertyAttribute = new(
        id: "VF10013",
        title: "Invalid VersionProperty attribute",
        messageFormat: "VersionProperty attribute '{0}' cannot be applied to generated property '{1}': {2}",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    // Data synchronization diagnostics (VS10001-VS10004)
    public static readonly DiagnosticDescriptor VS10001_UnsupportedSyncType = new(
        id: "VS10001",
        title: "Unsupported synced field type",
        messageFormat: "[VersionField] '{0}' in an IVersionSync class has type '{1}' which cannot be synchronized. Use a primitive/enum/string, a nested concrete IVersionSync type, or a Version container.",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor VS10002_SyncTypeMissingPublicParameterlessConstructor = new(
        id: "VS10002",
        title: "Synced object type missing public parameterless constructor",
        messageFormat: "Synced object type '{0}' used by [VersionField] '{1}' must have a public parameterless constructor so synchronization can create it when applying data.",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor VS10003_SyncTypeMustBeConcrete = new(
        id: "VS10003",
        title: "Synchronized object type must be concrete",
        messageFormat: "[VersionField] '{0}' uses '{1}' as a synchronized {2}. Use a concrete, non-abstract IVersionSync class because Apply must construct the field's static type.",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor VS10004_DictionaryKeyMustBeScalar = new(
        id: "VS10004",
        title: "Synchronized dictionary key must be scalar",
        messageFormat: "[VersionField] '{0}' uses unsupported dictionary key type '{1}'. VersionSyncDictionary keys must be primitive, enum, decimal, or string values; put IVersionSync objects in the value instead.",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

}
